/**
 * esbuild config for the Randomness plugin.
 *
 * Usage:
 *   node esbuild.config.mjs              # dev — watches files, inline sourcemap
 *   node esbuild.config.mjs production   # release — minified, no sourcemap
 *
 * Output: main.js at the repo root, alongside manifest.json. That's
 * what Obsidian loads from .obsidian/plugins/randomness/main.js after
 * the user copies the files into their vault (or after BRAT installs
 * from this repo's releases).
 *
 * The `external` list mirrors what the official sample plugin
 * excludes — these are modules Obsidian provides at runtime, so
 * bundling them would bloat the output and break compatibility.
 */

import esbuild from "esbuild";
import process from "process";
// Use Node's own `module.builtinModules` rather than the
// `builtin-modules` npm package — it's been in core since Node
// 12.16 and removes a third-party dev dependency from the
// build chain. Same value (an array of built-in module names),
// no behaviour change.
import { builtinModules } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/views/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        // CodeMirror modules Obsidian provides at runtime. We don't
        // currently use any CM6 APIs but listing them future-proofs
        // the config against accidental bundling if a dependency
        // ever pulls them in transitively.
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
});

if (prod) {
    await context.rebuild();
    await context.dispose();
} else {
    await context.watch();
}
