/**
 * GENERATED FILE — do not edit.
 * Source: docs/guide/*.md. Regenerate: npm run embed-guide
 */

export const GUIDE_FOLDER = "Randomness Guide";

export interface GuideFile {
    name: string;
    content: string;
}

export const GUIDE_FILES: GuideFile[] = [
    {
        name: "01 - Roll Some Dice.md",
        content: "# 01 - Roll Some Dice\n\nEvery example here is live. 🎲 re-rolls, 🔒 keeps the result.\n\n## Plain rolls\n\n- One d20: `dice: 1d20`\n- With a bonus: `dice: 1d20 + 5`\n- Lots of dice: `dice: 8d6` (fireball!)\n- Don't know the die count? `dice: d20` means one d20.\n\n## The famous ones\n\n- **Advantage** (roll two d20, keep the best): `dice: 2d20kh`\n- **Disadvantage** (keep the worst): `dice: 2d20kl`\n- **Ability score** (roll 4d6, drop the lowest): `dice: 4d6dl1`\n- **Exploding dice** (max roll = roll again and add): `dice: 3d6!`\n- **Re-roll 1s once**: `dice: 2d6r`\n- **Count successes** (how many dice rolled 5+): `dice: 6d6>=5`\n\n## Special dice\n\n- Percentile: `dice: d%`\n- Traveller d66: `dice: 1d66%`\n- Fate/Fudge dice: `dice: 4dF`\n\n## Watch them tumble\n\nAdd `|render` and the dice animate: `dice: 4d6dl1|render`\n\n(Turn animations on or off in Settings → Randomness →\nGraphical dice.)\n\n## Dice inside sentences and tables\n\nInside generator text, dice go in curly braces:\n\n```randomness\nTable: Loot\nYou find {2d6} gold coins and {1d4} shiny buttons.\n```\n\n## Name your favourite rolls\n\nOpen **Settings → Randomness → Dice formula aliases** and add:\n\n```text\nsneak = 4d6dl1\n```\n\nNow `dice: sneak` rolls it. The ★ button in the dice tray saves\nformulas to the same list.\n\n## Cheat sheet\n\n| Write | Get |\n| ----- | --- |\n| `2d6 + 3` | two d6 plus 3 |\n| `2d20kh` / `2d20kl` | keep highest / lowest |\n| `4d6dl1` | drop the lowest die |\n| `3d6!` | exploding sixes |\n| `2d6r` | re-roll 1s once |\n| `6d6>=5` | count dice showing 5+ |\n| `d%`, `4dF`, `1d66%` | percentile, Fate, d66 |\n\nNext: [[02 - Random Tables In Your Notes]]\n",
    },
    {
        name: "02 - Random Tables In Your Notes.md",
        content: "# 02 - Random Tables In Your Notes\n\nAny markdown table or list becomes rollable when you give it a\nname. The name goes on the line under the table, starting with\n`^` (that's an Obsidian \"block id\").\n\n## A simple table\n\n| Tavern |\n| ------ |\n| The Prancing Pony |\n| The Rusty Bucket |\n| The Laughing Ghost |\n| The Drunken Goblin |\n\n^taverns\n\nTonight you sleep at `rdm:[@taverns]`.\n\nRoll three at once: `rdm:3[[02 - Random Tables In Your Notes^taverns]]`\n\n## Lists work too\n\n- it starts to rain\n- a dog follows you\n- you smell fresh bread\n- someone is watching\n\n^events\n\nOn the way: `rdm:[@events]`\n\n## Tables with columns\n\n| Name  | Job       | Secret |\n| ----- | --------- | ------ |\n| Alia  | baker     | afraid of yeast |\n| Borin | guard     | writes poetry |\n| Cass  | herbalist | can't smell anything |\n\n^npcs\n\n- Whole row: `rdm:[@npcs]`\n- Just a name: `rdm:[@npcs.Name]`\n- Any random cell: `rdm:[@npcs.xy]`\n\n## Lookup tables (roll dice, read the row)\n\nMake the first column a dice formula and give rows number ranges:\n\n| dice: 1d20 | What happens |\n| ---------- | ------------ |\n| 1-2        | Ambush! {1d4} bandits jump out |\n| 3-10       | A quiet mile |\n| 11-17      | A traveller waves hello |\n| 18-20      | You find {2d6} coins on the road |\n\n^road\n\nOn the road: `rdm:[@road]`\n\nNotice the `{1d4}` inside a row — tables can roll dice (and even\nother tables) inside their results. Rollers all the way down.\n\n## Rolling from other notes\n\nFrom any other note, name the note too:\n\n```text\n`rdm:[[02 - Random Tables In Your Notes^taverns]]`\n```\n\nNext: [[03 - Lock It In]]\n",
    },
    {
        name: "03 - Lock It In.md",
        content: "# 03 - Lock It In\n\nRolls change every time a note re-renders. When you get a result\nyou want to KEEP — a name, a shop, a plot twist — lock it.\n\n## Try it\n\nYour rival's name is `rdm:[@rivals]`.\n\n| Rival |\n| ----- |\n| Ember the Unpaid |\n| Sir Reginald Crumb |\n| Two Ferrets In A Coat |\n| Madame Halibut |\n\n^rivals\n\nHover the result and click 🔒. Done — that result is now written\ninto your note itself. It survives closing Obsidian, syncing to\nyour phone, everything. Click 🎲 on a locked roll to unlock and\nroll fresh.\n\nPeek at this note in source mode after locking: you'll see the\nresult stored right in the text, after a `⟹` arrow. It's your\nnote, not hidden plugin data.\n\n## Lock everything at once\n\nTwo commands (Ctrl/Cmd+P):\n\n- **Lock all rdm: in current note** — locks every unfilled roll,\n  keeping exactly what's on screen.\n- **Reroll all rdm: in current note** — unlocks everything for a\n  fresh start.\n\n## Rolls that lock themselves\n\n`dice-mod:` rolls once and locks immediately — the first time the\nnote renders, the result is written in and stays:\n\n```text\nTreasure: `dice-mod: 2d6 * 10` gold\n```\n\nGreat for loot you generate once and never want to change.\n\nNext: [[04 - Random Lines, Blocks and Tags]]\n",
    },
    {
        name: "04 - Random Lines, Blocks and Tags.md",
        content: "# 04 - Random Lines, Blocks and Tags\n\nYou don't even need a table. Randomness can pick from whole\nnotes.\n\n## A random line or paragraph from a note\n\n```text\n`rdm:[[Rumour Mill|line]]`    one random line from that note\n`rdm:[[Rumour Mill|block]]`   one random paragraph\n`rdm:3[[Rumour Mill|line]]`   three random lines\n```\n\nMake a note called \"Rumour Mill\", fill it with one rumour per\nline, and those calls work anywhere in your vault.\n\n## A random note with a tag\n\nTag some notes `#rumour` (in the text or in frontmatter). Then:\n\n```text\n`rdm:#rumour`        a random paragraph from a random tagged note\n`rdm:#rumour|link`   a link to a random tagged note\n```\n\nNo extra plugins needed — tags come from Obsidian itself.\n\n## Why this is handy\n\n- A `#quest-hook` tag across your campaign notes = instant\n  session starter.\n- A \"Overheard in the market\" note + `|line` = endless flavour.\n- `#npc|link` = \"who shows up?\" without building anything.\n\nNext: [[05 - Your First Generator File]]\n",
    },
    {
        name: "05 - Your First Generator File.md",
        content: "# 05 - Your First Generator File\n\nTables in notes are great. But when a generator gets big — or you\nwant to use it in every vault — put it in a **generator file**.\n\n## What is a .rdm file?\n\nJust a text file. Nothing magic. The `.rdm` ending tells\nRandomness \"this whole file is tables\". Obsidian opens and edits\nthem like any note.\n\n## The easy way to make one\n\nPress Ctrl/Cmd+P and run **\"Create new generator file\"**. That's\nit — Randomness makes the file (in your Generator root folder, if\nyou set one), fills in a starter template, and opens it for\nediting.\n\n## The manual way\n\nIf you'd rather do it by hand: create a text file anywhere in\nyour vault and make sure its name ends in `.rdm` (not `.md`, and\nnot `.rdm.txt`!).\n\n> **Windows tip:** Windows hides file endings by default, so your\n> \"MyTables.rdm\" might secretly be \"MyTables.rdm.txt\". In File\n> Explorer, turn on **View → File name extensions**, then rename.\n> Or skip all that and use the command above.\n\n## What goes inside\n\n```text\n// Lines starting with // are comments.\nTable: Weather\nsunny and warm\ngrey drizzle\nhowling wind\nthick fog\n\nTable: Mood\ncheerful\ngrumpy\nsuspiciously quiet\n```\n\n`Table:` starts a table; every line under it is one possible\nresult. The FIRST table in the file is the main one — rolling the\nfile rolls that table.\n\n## Rolling it\n\nAnywhere in any note:\n\n```text\n`rdm:[@Weather]`\n```\n\nNo setup needed — Randomness finds tables by name anywhere under\nyour Generator root. (Set that folder in Settings → Randomness;\nit keeps your generators tidy in one place.)\n\nOr roll from the sidebar: dice ribbon icon → find your file →\n**Roll**.\n\nNext: [[06 - Bigger Generators]]\n",
    },
    {
        name: "06 - Bigger Generators.md",
        content: "# 06 - Bigger Generators\n\nEverything here works in `.rdm` files AND in `randomness`\ncodeblocks inside notes. The examples below are live codeblocks —\nclick the edit icon on any of them to see the source.\n\n## Tables that call tables\n\n```randomness\nTable: Encounter\nA [@Monster] guards a [@Treasure].\n\nTable: Monster\ngrumpy troll\nsleepy dragon\nvery small ghost\n\nTable: Treasure\nchest of buttons\ngolden sandwich\nmap to somewhere\n```\n\n## Make some results rarer\n\nPut a number and a colon in front — higher numbers come up more:\n\n```randomness\nTable: Find\n10: a plain rock\n5: a shiny rock\n1: THE KING OF ROCKS\n```\n\n## Remember things with variables\n\n`Set:` remembers a roll so you can use it twice:\n\n```randomness\nTable: Villain\nSet: name=[@Name]\n{$name} raises an eyebrow. \"Yes,\" says {$name}, \"it was me.\"\n\nTable: Name\nDoctor Pickle\nLady Ravensworth\nThe Postman\n```\n\n## If this, then that\n\n```randomness\nTable: SavingThrow\nSet: roll={1d20}\nRolled {$roll}: [when]{$roll}>=10[do]You made it![else]You fell in the mud.[end]\n```\n\n## Ask the reader\n\n`Prompt:` adds a dropdown above the result:\n\n```randomness\nPrompt: Danger {Low|High} Low\nTable: Cave\n[when]{$Prompt1}=Low[do]Three bats and an echo.[else]The dragon is home. RUN.[end]\n```\n\n## Polish the output\n\nFilters clean up results — chain them with `>>`:\n\n```randomness\nTable: Shout\n[@Animal >> upper]!!!\n\nTable: Animal\nweasel\nheron\ncapybara\n```\n\nOther useful filters: `proper` (Title Case), `a` (adds \"a\"/\"an\"),\n`implode \", \"` (joins multiple rolls with commas), `bold`.\n\nThere's more — lookup tables, dictionaries, deck picks that never\nrepeat — all in the full reference (Settings → Randomness → Open\nreference).\n\nNext: [[07 - Sharing Tables Between Notes]]\n",
    },
    {
        name: "07 - Sharing Tables Between Notes.md",
        content: "# 07 - Sharing Tables Between Notes\n\nMade a great table? Use it everywhere.\n\n## The zero-setup way\n\nIf a table lives in a `.rdm` file under your **Generator root**\n(Settings → Randomness), just call it by name from any note:\n\n```text\n`rdm:[@TavernName]`\n```\n\nRandomness finds the file for you. Type `rdm:[@` and a popup even\nsuggests every table it knows — pick one and any needed imports\nare added automatically.\n\n## Borrowing tables from another note\n\nA note's block-id tables come along when you name the note:\n\n```text\n`rdm:[[Locations/Taverns^taverns]]`\n```\n\nOr bring ALL of another note's tables into this note with a\n`randomness` codeblock. Add a `Use:` line naming the note (shown\nhere indented so it displays instead of running):\n\n    ```randomness\n    Use: [[Locations/Taverns]]\n    Tonight: [@taverns]\n    ```\n\nAfter that `Use:` line, inline calls in the same note can see\nthose tables too.\n\n## The browser pane\n\nClick the dice ribbon icon. Every generator in your vault, in a\nfolder tree: **Roll** to try a table, 📋 to ",
    },
    {
        name: "08 - Coming From Dice Roller.md",
        content: "# 08 - Coming From Dice Roller\n\nUsed the Dice Roller plugin? Everything you wrote still works —\nRandomness speaks its language.\n\n1. Disable Dice Roller (Settings → Community plugins).\n2. Make sure Randomness is enabled.\n3. That's it. Your `dice:` rolls, table rolls, tag rolls, and\n   saved formulas all keep working.\n\nTry some classic Dice Roller syntax, live:\n\n- `dice: 1d20 + 5` — plain rolls\n- `dice: 4d6dl1` — modifiers\n- `dice: 3d6>=5` — success counting\n\nWhat you GAIN by switching: the 🔒 lock (results saved into your\nnotes — Dice Roller's saved results lived in plugin data and got\nlost), tag rolls without needing Dataview, and the whole\ngenerator engine underneath.\n\nThe full switching guide (including the few things that changed)\nis here:\n[migrating-from-dice-roller](https://github.com/Obsidian-TTRPG-Community/Randomness/blob/main/docs/migrating-from-dice-roller.md)\n\nNext: [[09 - Going Further]]\n",
    },
    {
        name: "09 - Going Further.md",
        content: "# 09 - Going Further\n\nYou know the essentials. Here's what else is in the box.\n\n## The full reference\n\nSettings → Randomness → **Open reference** — every feature, every\nsyntax, one searchable page. The deep version of this guide.\n\n## Portraits\n\nRandom character faces with rolled names, in codeblocks or inline.\nNeeds a one-click art pack: Settings → Randomness → **Install\nFantasy Portrait Pack**. Then try a `portrait` codeblock, or the\nPortraits and Builder tabs in the sidebar.\n\n## Fantasy Hub\n\nA showcase bundle: town generators plus ready-to-run Templater\ntemplates. Settings → Randomness → **Install Fantasy Hub\ncontent**.\n\n## Scripting\n\nOther plugins and Templater scripts can roll your tables:\n\n```text\napp.plugins.plugins[\"randomness\"].api\n```\n\nRoll a whole NPC into a fresh note from a template — see API.md\nin the repository for everything it can do.\n\n## Twenty years of tables\n\n`.rdm` files are the Inspiration Pad Pro format — the community\nhas been writing generators in it for two decades, and they load\nas-is (as do `.ipt` files). Search for \"inspiration pad\" tables\nand drop them into your Generator root.\n\nThat's the tour. Go roll something. 🎲\n",
    },
    {
        name: "Start Here.md",
        content: "# Start Here\n\nWelcome! Randomness rolls dice and picks random things from\ntables — right inside your notes.\n\nThere are three ways to roll. Try each one now — every example\non this page is **live**.\n\n## 1. Roll dice in a sentence\n\nType a dice roll between backticks, starting with `dice:`\n\nThe goblin hits you for `dice: 2d6 + 3` damage.\n\nClick the 🎲 to roll again. Click the 🔒 to keep the number\nforever.\n\n## 2. Roll on a table you made\n\nThis is a plain markdown table. The `^snacks` label underneath\ngives it a name:\n\n| Snack |\n| ----- |\n| a suspicious sandwich |\n| three olives on a sword |\n| cheese of unusual size |\n| one single, perfect grape |\n\n^snacks\n\nNow roll on it: you find `rdm:[@snacks]` in your bag.\n\n## 3. Use the dice tray\n\nClick the **dices icon** in the left ribbon (or press Ctrl/Cmd+P\nand run \"Open dice tray\"). Tap some dice, hit **Roll**, and watch\nthem tumble.\n\n## Where to next\n\n- [[01 - Roll Some Dice]] — every kind of dice roll\n- [[02 - Random Tables In Your Notes]] — make anything rollable\n- [[03 - Lock It In]] — keep the results you like\n- [[04 - Random Lines, Blocks and Tags]] — roll on whole notes\n- [[05 - Your First Generator File]] — reusable table files\n- [[06 - Bigger Generators]] — names, weights, if-this-then-that\n- [[07 - Sharing Tables Between Notes]] — one table, many notes\n- [[08 - Coming From Dice Roller]] — everything still works\n- [[09 - Going Further]] — portraits, scripting, big content packs\n\nDelete this folder whenever you like — it's just notes.\n",
    },
];
